CREATE OR REPLACE TABLE {{ params.table_name }} AS
/* Create a virtual table of all warehouses */
WITH VIRTUAL_WAREHOUSES AS (
    SELECT DISTINCT WAREHOUSE_NAME
    FROM {{ params.raw_metering_table }}
    WHERE WAREHOUSE_NAME IS NOT NULL
    ORDER BY WAREHOUSE_NAME
),

/* Create a cross product of all warehouses and all dates */
CROSS_PRODUCT AS (
    SELECT
        VW.WAREHOUSE_NAME,
        CALENDAR.USAGE_DATE
    FROM VIRTUAL_WAREHOUSES AS VW
    CROSS JOIN (
        SELECT USAGE_DATE
        FROM {{ params.common_calendar_table }}
        WHERE USAGE_DATE <= '{{ ds }}'
    ) AS CALENDAR
),

/* Join the metering data to the cross product to have a complete matrix */
METERING AS (
    SELECT
        CROSS_PRODUCT.WAREHOUSE_NAME,
        CROSS_PRODUCT.USAGE_DATE,
        COALESCE(SUM(METERING.CREDITS_USED), 0) AS CREDITS_USED,
        COALESCE(SUM(METERING.CREDITS_USED_COMPUTE), 0) AS CREDITS_USED_COMPUTE,
        COALESCE(SUM(METERING.CREDITS_USED_CLOUD_SERVICES), 0)
            AS CREDITS_USED_CLOUD_SERVICES
    FROM CROSS_PRODUCT
    LEFT JOIN {{ params.raw_metering_table }} AS METERING
        ON
            CROSS_PRODUCT.USAGE_DATE = METERING.USAGE_DATE
            AND CROSS_PRODUCT.WAREHOUSE_NAME = METERING.WAREHOUSE_NAME
    GROUP BY
        CROSS_PRODUCT.WAREHOUSE_NAME,
        CROSS_PRODUCT.USAGE_DATE
)

/* Compute Simple Moving averages and Standard Deviations */
SELECT
    WAREHOUSE_NAME,
    USAGE_DATE,
    CREDITS_USED,
    CREDITS_USED_COMPUTE,
    CREDITS_USED_CLOUD_SERVICES,
    AVG(CREDITS_USED) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY USAGE_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS CREDITS_USED_SMA30,
    AVG(CREDITS_USED_COMPUTE) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY USAGE_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS CREDITS_USED_COMPUTE_SMA30,
    AVG(CREDITS_USED_CLOUD_SERVICES) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY USAGE_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS CREDITS_USED_CLOUD_SERVICES_SMA30,
    STDDEV(CREDITS_USED) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY USAGE_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS CREDITS_USED_STD30,
    STDDEV(CREDITS_USED_COMPUTE) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY USAGE_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS CREDITS_USED_COMPUTE_STD30,
    STDDEV(CREDITS_USED_CLOUD_SERVICES) OVER (
        PARTITION BY WAREHOUSE_NAME
        ORDER BY USAGE_DATE
        ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
    ) AS CREDITS_USED_CLOUD_SERVICES_STD30
FROM METERING
ORDER BY
    WAREHOUSE_NAME,
    USAGE_DATE
