CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
	ACCOUNT_NAME VARCHAR(16777216),
	SERVICE_TYPE VARCHAR(25),
	USAGE_DATE DATE,
	WAREHOUSE_NAME VARCHAR(16777216),
	CREDITS_USED NUMBER(38,9),
	CREDITS_USED_COMPUTE NUMBER(38,9),
	CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
	UPDATED_AT TIMESTAMP_NTZ(9)
);
