CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
	WAREHOUSE_NAME VARCHAR(16777216),
	USAGE_DATE VARCHAR(16777216),
	CREDITS_USED FLOAT,
	TREND FLOAT,
	SEASONAL FLOAT,
	RESIDUAL FLOAT,
	SCORE FLOAT,
	PREDICTION_DATETIME TIMESTAMP_NTZ(9)
);
