CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
	USAGE_DATE DATE,
	DATABASE_ID NUMBER(38,0),
	DATABASE_NAME VARCHAR(16777216),
	DATABASE_BYTES FLOAT,
	DATABASE_STORAGE_COST FLOAT,
	LAST_UPDATED_AT TIMESTAMP_NTZ(9)
);
