CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    WAREHOUSE_NAME VARCHAR(),
    USAGE_DATE VARCHAR(),
    CREDITS_USED FLOAT,
    TREND FLOAT,
    SEASONAL FLOAT,
    RESIDUAL FLOAT,
    SCORE FLOAT,
    PREDICTION_DATETIME TIMESTAMP_NTZ(9),
    DS DATE
);
