CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    ACCOUNT_NAME VARCHAR(),
    SERVICE_TYPE VARCHAR(25),
    USAGE_DATE DATE,
    WAREHOUSE_NAME VARCHAR(),
    CREDITS_USED NUMBER(38, 9),
    CREDITS_USED_COMPUTE NUMBER(38, 9),
    CREDITS_USED_CLOUD_SERVICES NUMBER(38, 9),
    DS DATE
);
