CREATE TABLE IF NOT EXISTS {{ params.table_name }} (
    USAGE_DATE DATE,
    DATABASE_ID NUMBER(38, 0),
    DATABASE_NAME VARCHAR(),
    DATABASE_BYTES FLOAT,
    DATABASE_TERABYTES FLOAT,
    DATABASE_STORAGE_COST FLOAT,
    DS DATE
);
