CREATE OR REPLACE VIEW {{ params.view_name }} AS (
WITH TODAY AS (
    SELECT
    D.AIRFLOW_DAG_ID,
    D.AIRFLOW_TASK_ID,
    D.DS,
    D.WAREHOUSE_NAME,
    SUM(D.TASK_DOLLAR_COST) AS TASK_DOLLAR_COST,
    SUM(D.TASK_CREDIT_COST) AS TASK_CREDIT_COST
    FROM {{ params.reporting_dag_cost }} D
    WHERE
      (D.DS = (SELECT MAX(DS) FROM {{ params.reporting_dag_cost }})
    OR  D.DS = (SELECT MAX(DS)-1 FROM {{ params.reporting_dag_cost }})
    AND D.AIRFLOW_TASK_ID IS NOT NULL
    GROUP BY 1, 2, 3, 4
), YESTERDAY AS (
    SELECT
    D.AIRFLOW_DAG_ID,
    D.AIRFLOW_TASK_ID,
    D.DS,
    D.WAREHOUSE_NAME,
    SUM(D.TASK_DOLLAR_COST) AS TASK_DOLLAR_COST,
    SUM(D.TASK_CREDIT_COST) AS TASK_CREDIT_COST
    FROM {{ params.reporting_dag_cost }} D
    WHERE
      (D.DS = DATEADD(DAY, -1, (SELECT MAX(DS) FROM {{ params.reporting_dag_cost }})
    OR  D.DS = DATEADD(DAY, -1, (SELECT MAX(DS)-1 FROM {{ params.reporting_dag_cost }}))
    AND D.AIRFLOW_TASK_ID IS NOT NULL
    GROUP BY 1, 2, 3, 4
), LAST_WEEK AS (
    SELECT
    D.AIRFLOW_DAG_ID,
    D.AIRFLOW_TASK_ID,
    D.DS,
    D.WAREHOUSE_NAME,
    SUM(D.TASK_DOLLAR_COST) AS TASK_DOLLAR_COST,
    SUM(D.TASK_CREDIT_COST) AS TASK_CREDIT_COST
    FROM {{ params.reporting_dag_cost }} D
    WHERE
      (D.DS = DATEADD(DAY, -7, (SELECT MAX(DS) FROM {{ params.reporting_dag_cost }}))
    OR  D.DS = DATEADD(DAY, -7, (SELECT MAX(DS)-1 FROM {{ params.reporting_dag_cost }})))
    AND D.AIRFLOW_TASK_ID IS NOT NULL
    GROUP BY 1, 2, 3, 4
), LAST_MONTH AS (
    SELECT
    D.AIRFLOW_DAG_ID,
    D.AIRFLOW_TASK_ID,
    D.DS,
    D.WAREHOUSE_NAME,
    SUM(D.TASK_DOLLAR_COST) AS TASK_DOLLAR_COST,
    SUM(D.TASK_CREDIT_COST) AS TASK_CREDIT_COST
    FROM {{ params.reporting_dag_cost }} D
    WHERE
      (D.DS = DATEADD(DAY, -28, (SELECT MAX(DS) FROM {{ params.reporting_dag_cost }}))
    OR  D.DS = DATEADD(DAY, -28, (SELECT MAX(DS)-1 FROM {{ params.reporting_dag_cost }})))
    AND D.AIRFLOW_TASK_ID IS NOT NULL
    GROUP BY 1, 2, 3, 4
), YESTERDAY_WARNING AS (
    SELECT
        T.DS,
        D.AIRFLOW_DAG_ID,
        D.AIRFLOW_TASK_ID,
        T.WAREHOUSE_NAME,
        T.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_TODAY,
        T.TASK_CREDIT_COST AS TASK_CREDIT_COST_TODAY,
        Y.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_YESTERDAY,
        Y.TASK_CREDIT_COST AS TASK_CREDIT_COST_YESTERDAY,
        LW.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_LAST_WEEK,
        LW.TASK_CREDIT_COST AS TASK_CREDIT_COST_LAST_WEEK,
        LM.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_LAST_MONTH,
        LM.TASK_CREDIT_COST AS TASK_CREDIT_COST_LAST_MONTH,
        T.TASK_DOLLAR_COST - Y.TASK_DOLLAR_COST AS YESTERDAY_WARN_DOLLAR_DELTA_YESTERDAY,
        T.TASK_CREDIT_COST - Y.TASK_CREDIT_COST AS YESTERDAY_WARN_CREDIT_DELTA_YESTERDAY,
        T.TASK_DOLLAR_COST - LW.TASK_DOLLAR_COST AS YESTERDAY_WARN_DOLLAR_DELTA_LAST_WEEK,
        T.TASK_CREDIT_COST - LW.TASK_CREDIT_COST AS YESTERDAY_WARN_CREDIT_DELTA_LAST_WEEK,
        T.TASK_DOLLAR_COST - LM.TASK_DOLLAR_COST AS YESTERDAY_WARN_DOLLAR_DELTA_LAST_MONTH,
        T.TASK_CREDIT_COST - LM.TASK_CREDIT_COST AS YESTERDAY_WARN_CREDIT_DELTA_LAST_MONTH,
        T.TASK_CREDIT_COST/NULLIF(Y.TASK_CREDIT_COST,0)-1 AS YESTERDAY_WARN_PCT_CHANGE_YESTERDAY,
        T.TASK_CREDIT_COST/NULLIF(LW.TASK_CREDIT_COST,0)-1 AS YESTERDAY_WARN_PCT_CHANGE_LAST_WEEK,
        T.TASK_CREDIT_COST/NULLIF(LM.TASK_CREDIT_COST,0)-1 AS YESTERDAY_WARN_PCT_CHANGE_LAST_MONTH
    FROM TODAY T
    LEFT JOIN YESTERDAY Y
        ON T.AIRFLOW_TASK_ID = Y.AIRFLOW_TASK_ID
        AND T.DAG_NAME = Y.DAG_NAME
        AND T.DS = DATEADD(DAY, 1, Y.DS)
    LEFT JOIN LAST_WEEK LW
        ON T.AIRFLOW_TASK_ID = LW.AIRFLOW_TASK_ID
        AND T.DAG_NAME = LW.DAG_NAME
        AND T.DS = DATEADD(DAY, 7, LW.DS)
    LEFT JOIN LAST_MONTH LM
        ON T.AIRFLOW_TASK_ID = LM.AIRFLOW_TASK_ID
        AND T.DAG_NAME = LM.DAG_NAME
        AND T.DS = DATEADD(DAY, 28, LM.DS)
    WHERE T.DS = (SELECT MAX(DS)-1 FROM {{ params.reporting_dag_cost }})
)

SELECT
T.DS,
T.AIRFLOW_DAG_ID,
T.AIRFLOW_TASK_ID,
T.WAREHOUSE_NAME,
T.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_TODAY,
T.TASK_CREDIT_COST AS TASK_CREDIT_COST_TODAY,
Y.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_YESTERDAY,
Y.TASK_CREDIT_COST AS TASK_CREDIT_COST_YESTERDAY,
LW.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_LAST_WEEK,
LW.TASK_CREDIT_COST AS TASK_CREDIT_COST_LAST_WEEK,
LM.TASK_DOLLAR_COST AS TASK_DOLLAR_COST_LAST_MONTH,
LM.TASK_CREDIT_COST AS TASK_CREDIT_COST_LAST_MONTH,
T.TASK_DOLLAR_COST - Y.TASK_DOLLAR_COST AS DOLLAR_DELTA_YESTERDAY,
T.TASK_CREDIT_COST - Y.TASK_CREDIT_COST AS CREDIT_DELTA_YESTERDAY,
T.TASK_DOLLAR_COST - LW.TASK_DOLLAR_COST AS DOLLAR_DELTA_LAST_WEEK,
T.TASK_CREDIT_COST - LW.TASK_CREDIT_COST AS CREDIT_DELTA_LAST_WEEK,
T.TASK_DOLLAR_COST - LM.TASK_DOLLAR_COST AS DOLLAR_DELTA_LAST_MONTH,
T.TASK_CREDIT_COST - LM.TASK_CREDIT_COST AS CREDIT_DELTA_LAST_MONTH,
T.TASK_CREDIT_COST/NULLIF(Y.TASK_CREDIT_COST,0)-1 AS PCT_CHANGE_YESTERDAY,
T.TASK_CREDIT_COST/NULLIF(LW.TASK_CREDIT_COST,0)-1 AS PCT_CHANGE_LAST_WEEK,
T.TASK_CREDIT_COST/NULLIF(LM.TASK_CREDIT_COST,0)-1 AS PCT_CHANGE_LAST_MONTH,
YESTERDAY_WARN_DOLLAR_DELTA_YESTERDAY,
YESTERDAY_WARN_CREDIT_DELTA_YESTERDAY,
YESTERDAY_WARN_DOLLAR_DELTA_LAST_WEEK,
YESTERDAY_WARN_CREDIT_DELTA_LAST_WEEK,
YESTERDAY_WARN_DOLLAR_DELTA_LAST_MONTH,
YESTERDAY_WARN_CREDIT_DELTA_LAST_MONTH,
YESTERDAY_WARN_PCT_CHANGE_YESTERDAY,
YESTERDAY_WARN_PCT_CHANGE_LAST_WEEK,
YESTERDAY_WARN_PCT_CHANGE_LAST_MONTH
FROM TODAY T
LEFT JOIN YESTERDAY Yas
    ON T.AIRFLOW_TASK_ID = Y.AIRFLOW_TASK_ID
    AND T.DAG_NAME = Y.DAG_NAME
    AND T.DS = DATEADD(DAY, 1, Y.DS)
LEFT JOIN LAST_WEEK LW
    ON T.AIRFLOW_TASK_ID = LW.AIRFLOW_TASK_ID
    AND T.DAG_NAME = LW.DAG_NAME
    AND T.DS = DATEADD(DAY, 7, LW.DS)
LEFT JOIN LAST_MONTH LM
    ON T.AIRFLOW_TASK_ID = LM.AIRFLOW_TASK_ID
    AND T.DAG_NAME = LM.DAG_NAME
    AND T.DS = DATEADD(DAY, 28, LM.DS)
LEFT JOIN YESTERDAY_WARNING YW
    ON T.AIRFLOW_TASK_ID = YW.AIRFLOW_TASK_ID
    AND T.DAG_NAME = YW.DAG_NAME
WHERE T.DS = (SELECT MAX(DS) FROM {{ params.reporting_dag_cost }})
);
