DELETE FROM {{ params.reporting_warehouse_credits }}
WHERE DS = '{{ ds }}';

INSERT INTO {{ params.reporting_warehouse_credits }}
WITH TOTAL_WAREHOUSE_TIME AS (
    SELECT
        WAREHOUSE_NAME,
        SUM(TOTAL_ELAPSED_TIME) AS TOTAL_TIME_ELAPSED
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE TO_DATE(END_TIME::TIMESTAMP_TZ) = '{{ ds }}'
    GROUP BY WAREHOUSE_NAME
),

WAREHOUSE_COST AS (
    SELECT
        WAREHOUSE_NAME,
        SUM(CREDITS_USED) AS WAREHOUSE_CREDITS
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE
        START_TIME >= '{{ ds }}'::TIMESTAMP_TZ
        AND END_TIME
        <= DATEADD(NANOSECOND, -1, DATEADD(DAY, 1, '{{ ds }}'::TIMESTAMP_TZ))
    GROUP BY WAREHOUSE_NAME
),

WAREHOUSE_COMPUTE_RATE AS (
    SELECT EFFECTIVE_RATE
    FROM SNOWFLAKE.ORGANIZATION_USAGE.RATE_SHEET_DAILY
    WHERE
        ACCOUNT_NAME = '{{ params.account_number }}'
        AND USAGE_TYPE = 'compute'
        AND TO_DATE(DATE::TIMESTAMP_TZ) = '{{ ds }}'
)

SELECT
    T.WAREHOUSE_NAME,
    C.WAREHOUSE_CREDITS,
    T.TOTAL_TIME_ELAPSED,
    R.EFFECTIVE_RATE,
    '{{ ds }}' AS DS
FROM TOTAL_WAREHOUSE_TIME AS T
INNER JOIN WAREHOUSE_COST AS C
    ON T.WAREHOUSE_NAME = C.WAREHOUSE_NAME
INNER JOIN WAREHOUSE_COMPUTE_RATE AS R
