DELETE FROM {{ params.reporting_database_storage_cost }}
WHERE DS = '{{ ds }}';

INSERT INTO {{ params.reporting_database_storage_cost }}
SELECT
    U.USAGE_DATE,
    U.DATABASE_ID,
    U.DATABASE_NAME,
    U.AVERAGE_DATABASE_BYTES AS DATABASE_BYTES,
    (DATABASE_BYTES / POWER(1024, 4)) AS DATABASE_TERABYTES,
    R.EFFECTIVE_RATE * DATABASE_TERABYTES AS DATABASE_STORAGE_COST,
    '{{ ds }}' AS DS
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY AS U
LEFT JOIN SNOWFLAKE.ORGANIZATION_USAGE.RATE_SHEET_DAILY AS R
    ON U.USAGE_DATE = R.DATE
WHERE
    R.ACCOUNT_NAME = 'GP21411'
    AND R.USAGE_TYPE = 'storage'
    AND U.USAGE_DATE = '{{ ds }}'
ORDER BY U.DATABASE_NAME, U.USAGE_DATE
