# Set the following GitHub Secrets before running the GitHub Actions Workflow for the first time:
# - DEV_ASTRO_DEPLOYMENT_ID
# - DEV_ASTRO_API_TOKEN
# - PROD_ASTRO_DEPLOYMENT_ID
# - PROD_ASTRO_API_TOKEN

name: Astro Deploy

on:
    pull_request:
      branches:
        - dev
        - main
      types: [ closed ]

jobs:
  astro-deploy-dev:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      ASTRO_API_TOKEN: ${{ secrets.DEV_ASTRO_API_TOKEN }}
    steps:
    - name: Deploy to Astro Dev
      uses: astronomer/deploy-action@v0.4
      with:
        deployment-id: ${{ secrets.DEV_ASTRO_DEPLOYMENT_ID }}

  astro-deploy-prod:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      ASTRO_API_TOKEN: ${{ secrets.PROD_ASTRO_API_TOKEN }}
    steps:
    - name: Deploy to Astro Prod
      uses: astronomer/deploy-action@v0.4
      with:
        deployment-id: ${{ secrets.PROD_ASTRO_DEPLOYMENT_ID }}
